version: '1.0'
services:
  app:
    container_name: 'url_shortener'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mysql://root:root@localhost:3306/testdb
    volumes:
      - ./data/app
  
  mysql-1:
    container_name: mysql-1
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testdb
    volumes:
      - ./data/mysql-1:/var/lib/mysql